// Auto-generated by the postman-to-k6 converter

import "./libs/shim/core.js";
import "./libs/shim/urijs.js";
import URI from "./libs/urijs.js";
import { group } from "k6";

export const options = {
  maxRedirects: 4,
  duration: "1m",
  vus: 10,
  thresholds: {
    http_req_failed: ["rate<0.02"], // http errors should be less than 2%
    http_req_duration: ["p(95)<2000"], // 95% requests should be below 2s
  },
  scenarios: {
    constant_request_rate: {
      executor: "constant-arrival-rate",
      rate: 1000,
      timeUnit: "1s", // 1000 iterations per second, i.e. 1000 RPS
      duration: "5m",
      preAllocatedVUs: 5, // how large the initial pool of VUs would be
      maxVUs: 10, // if the preAllocatedVUs are not enough, we can initialize more
    },
  },
};

const Request = Symbol.for("request");
postman[Symbol.for("initial")]({
  options,
  environment: {
    "base_url.be": "http://localhost:3000",
    "base_url.kong": "http://10.211.55.8:8000",
    "base_url.post-be": "http://10.211.55.1:4000",
    "base_url.comment-be": "http://localhost:4001",
    "base_url.apisix": "http://10.211.55.10:9080",
  },
});

export default function () {
  group("BACKEND", function () {
    group("POST", function () {
      postman[Request]({
        name: "Create Post",
        id: "96a5a3aa-38c6-4991-b6a9-78634f4ed85f",
        method: "POST",
        address: "{{base_url.post-be}}/post",
        data: "{{backend.create.post.request-body}}",
        pre() {
          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.create.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post",
        id: "21924743-5a37-4249-b032-a6c7d2da264e",
        method: "GET",
        address: "{{base_url.post-be}}/post",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const post = responseJSON.results[0];
            if (post.id !== "") {
              pm.environment.set(
                "backend.get.post.response-body.latest",
                JSON.stringify(post)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post Detail",
        id: "636c07f7-2116-4800-b504-afe9893f0601",
        method: "GET",
        address:
          "{{base_url.post-be}}/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Post",
        id: "5246d99a-19aa-42cb-b3d2-5eb4b231e6b3",
        method: "PUT",
        address:
          "{{base_url.post-be}}/post/{{backend.get.post.response-body.latest.id}}",
        data: "{{backend.update.post.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );

          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.update.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Post",
        id: "ed568933-7bc9-47af-9fb0-4643814eb9d6",
        method: "DELETE",
        address:
          "{{base_url.post-be}}/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    group("COMMENT", function () {
      postman[Request]({
        name: "Create Comment",
        id: "6f899508-fb4a-4e67-a07a-a27e978af8e8",
        method: "POST",
        address: "{{base_url.comment-be}}/comment",
        data: "{{backend.create.comment.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            post_id: post.id,
            body: body,
          };

          pm.environment.set(
            "backend.create.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment",
        id: "143c18e6-e4da-43dc-b808-dff7c36d8d3c",
        method: "GET",
        address: "{{base_url.comment-be}}/comment",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const comment = responseJSON.results[0];
            if (comment.id !== "") {
              pm.environment.set(
                "backend.get.comment.response-body.latest",
                JSON.stringify(comment)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment Detail",
        id: "f9daa6ea-5b94-4dec-aebc-cafa1fe84180",
        method: "GET",
        address:
          "{{base_url.comment-be}}/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Comment",
        id: "5fc52d65-6d81-4b13-8449-244203f66abe",
        method: "PUT",
        address:
          "{{base_url.comment-be}}/comment/{{backend.get.comment.response-body.latest.id}}",
        data: "{{backend.update.comment.request-body}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );

          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            body: body,
          };

          pm.environment.set(
            "backend.update.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Comment",
        id: "dc96b12c-0516-49c2-9693-4cd6530ebbb8",
        method: "DELETE",
        address:
          "{{base_url.comment-be}}/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    postman[Request]({
      name: "Sign-In",
      id: "8f60fde0-d1f8-483a-8b4b-27d8102b0304",
      method: "POST",
      address: "{{base_url.be}}/api/v1/auth/sign-in",
      auth(config, Var) {
        const address = new URI(config.address);
        address.username(`${pm[Var]("username")}`);
        address.password(`${pm[Var]("password")}`);
        config.address = address.toString();
        config.options.auth = "basic";
      },
    });
  });

  group("KONG BACKEND", function () {
    group("POST", function () {
      postman[Request]({
        name: "Create Post",
        id: "5d51248b-17cf-43f3-ba42-be53d264d1ca",
        method: "POST",
        address: "{{base_url.kong}}/api/v1/post",
        data: "{{backend.create.post.request-body}}",
        pre() {
          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.create.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post",
        id: "c6c739c5-8a45-4fa8-b71f-d09d59d5e0f3",
        method: "GET",
        address: "{{base_url.kong}}/api/v1/post",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const post = responseJSON.results[0];
            if (post.id !== "") {
              pm.environment.set(
                "backend.get.post.response-body.latest",
                JSON.stringify(post)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post Detail",
        id: "a122a31b-dbe1-4767-bf98-41717ea882f0",
        method: "GET",
        address:
          "{{base_url.kong}}/api/v1/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Post",
        id: "52029ad6-7ffb-4f7a-b92f-364e53c6ead0",
        method: "PUT",
        address:
          "{{base_url.kong}}/api/v1/post/{{backend.get.post.response-body.latest.id}}",
        data: "{{backend.update.post.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );

          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.update.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Post",
        id: "d547d9b7-dd18-416e-8af4-9c6bafe06587",
        method: "DELETE",
        address:
          "{{base_url.kong}}/api/v1/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    group("COMMENT", function () {
      postman[Request]({
        name: "Create Comment",
        id: "e98dacc2-41ce-49ce-8cf9-7d5832a3f6cd",
        method: "POST",
        address: "{{base_url.kong}}/api/v1/comment",
        data: "{{backend.create.comment.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            post_id: post.id,
            body: body,
          };

          pm.environment.set(
            "backend.create.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment",
        id: "4319971c-244d-4c30-b4da-7d11793273dc",
        method: "GET",
        address: "{{base_url.kong}}/api/v1/comment",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const comment = responseJSON.results[0];
            if (comment.id !== "") {
              pm.environment.set(
                "backend.get.comment.response-body.latest",
                JSON.stringify(comment)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment Detail",
        id: "05835ad7-d219-4f90-8d45-12ec2171ca70",
        method: "GET",
        address:
          "{{base_url.kong}}/api/v1/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Comment",
        id: "3c77601a-b51c-4149-88b4-addb5d835559",
        method: "PUT",
        address:
          "{{base_url.kong}}/api/v1/comment/{{backend.get.comment.response-body.latest.id}}",
        data: "{{backend.update.comment.request-body}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );

          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            body: body,
          };

          pm.environment.set(
            "backend.update.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Comment",
        id: "248e7b1f-9868-48c0-af95-bf84ef1bf630",
        method: "DELETE",
        address:
          "{{base_url.kong}}/api/v1/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    postman[Request]({
      name: "Sign-In",
      id: "5fc38975-cccc-4e67-940f-42e0d281ee1c",
      method: "POST",
      address: "{{base_url.be}}/api/v1/auth/sign-in",
      auth(config, Var) {
        const address = new URI(config.address);
        address.username(`${pm[Var]("username")}`);
        address.password(`${pm[Var]("password")}`);
        config.address = address.toString();
        config.options.auth = "basic";
      },
    });
  });

  group("APISIX BACKEND", function () {
    group("POST", function () {
      postman[Request]({
        name: "Create Post",
        id: "bc95ad0e-df0c-4130-b1bd-bf746c7d0343",
        method: "POST",
        address: "{{base_url.apisix}}/post",
        data: "{{backend.create.post.request-body}}",
        pre() {
          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.create.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post",
        id: "0d9a384a-d18f-4cfb-81e0-78f3096a48e2",
        method: "GET",
        address: "{{base_url.apisix}}/post",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const post = responseJSON.results[0];
            if (post.id !== "") {
              pm.environment.set(
                "backend.get.post.response-body.latest",
                JSON.stringify(post)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Post Detail",
        id: "48f952a4-6d83-4682-aaf8-bf1ba2d5f9d9",
        method: "GET",
        address:
          "{{base_url.apisix}}/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Post",
        id: "99a89241-0b7c-42d3-9030-2ef993e8e008",
        method: "PUT",
        address:
          "{{base_url.apisix}}/post/{{backend.get.post.response-body.latest.id}}",
        data: "{{backend.update.post.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );

          const title = pm.variables.replaceIn("{{$randomUserName}}");
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            title: `POST ${title}`,
            body: body,
          };

          pm.environment.set(
            "backend.update.post.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Post",
        id: "32dfc36d-31a2-4213-a715-4c86de5c4680",
        method: "DELETE",
        address:
          "{{base_url.apisix}}/post/{{backend.get.post.response-body.latest.id}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          pm.environment.set(
            "backend.get.post.response-body.latest.id",
            post.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    group("COMMENT", function () {
      postman[Request]({
        name: "Create Comment",
        id: "752c69f4-f38b-4451-9831-56b2742a19e4",
        method: "POST",
        address: "{{base_url.apisix}}/comment",
        data: "{{backend.create.comment.request-body}}",
        pre() {
          const post = JSON.parse(
            pm.environment.get("backend.get.post.response-body.latest")
          );
          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            post_id: post.id,
            body: body,
          };

          pm.environment.set(
            "backend.create.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment",
        id: "15932933-ab43-418a-8307-8990d85500cd",
        method: "GET",
        address: "{{base_url.apisix}}/comment",
        post(response) {
          const responseJSON = pm.response.json();

          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });

          pm.test("Save Latest Response", function () {
            const comment = responseJSON.results[0];
            if (comment.id !== "") {
              pm.environment.set(
                "backend.get.comment.response-body.latest",
                JSON.stringify(comment)
              );
            }
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Get List Comment Detail",
        id: "ac969c6f-e234-42fd-b844-df6e0003ac82",
        method: "GET",
        address:
          "{{base_url.apisix}}/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Update Comment",
        id: "0716bdb3-2e9b-4663-8ab0-024e27742b77",
        method: "PUT",
        address:
          "{{base_url.apisix}}/comment/{{backend.get.comment.response-body.latest.id}}",
        data: "{{backend.update.comment.request-body}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );

          const body = pm.variables.replaceIn("{{$randomLoremText}}");

          const requestJSON = {
            body: body,
          };

          pm.environment.set(
            "backend.update.comment.request-body",
            JSON.stringify(requestJSON)
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });

      postman[Request]({
        name: "Delete Comment",
        id: "7ae7a6e3-2400-4b25-a156-3c51b341f97a",
        method: "DELETE",
        address:
          "{{base_url.apisix}}/comment/{{backend.get.comment.response-body.latest.id}}",
        pre() {
          const comment = JSON.parse(
            pm.environment.get("backend.get.comment.response-body.latest")
          );
          pm.environment.set(
            "backend.get.comment.response-body.latest.id",
            comment.id
          );
        },
        post(response) {
          pm.test("Status code is 200", function () {
            pm.response.to.have.status(200);
          });
        },
      });
    });

    postman[Request]({
      name: "Sign-In",
      id: "57d8e96f-e519-41f4-9161-1bbfd0c1430c",
      method: "POST",
      address: "{{base_url.be}}/api/v1/auth/sign-in",
      auth(config, Var) {
        const address = new URI(config.address);
        address.username(`${pm[Var]("username")}`);
        address.password(`${pm[Var]("password")}`);
        config.address = address.toString();
        config.options.auth = "basic";
      },
    });
  });

  group("APISIX", function () {});

  group("KONG", function () {
    postman[Request]({
      name: "Sign-In",
      id: "5f1e99d6-7801-4b72-b324-83e74bad2b00",
      method: "POST",
      address: "{{base_url.kong}}/kong-bku-auth/bku/v1/web/auth/login",
      auth(config, Var) {
        const address = new URI(config.address);
        address.username(`${pm[Var]("username")}`);
        address.password(`${pm[Var]("password")}`);
        config.address = address.toString();
        config.options.auth = "basic";
      },
    });
  });

  group("TYK", function () {});
}
